// ========== Internationalization (i18n) ==========
// French is the default language (in the HTML).
// English translations generated by AI (Claude).

const translations = {
  fr: {
    // Nav
    'nav.home': 'Accueil',
    'nav.about': 'A propos',
    'nav.skills': 'Competences',
    'nav.projects': 'Projets',
    'nav.contact': 'Contact',

    // Hero
    'hero.greeting': 'Bonjour, je suis',
    'hero.title': 'Developpeur <span class="accent">Full Stack</span>',
    'hero.desc': 'Je cree des experiences web modernes avec un code propre et un design creatif.',
    'hero.cta1': 'Voir mes projets',
    'hero.cta2': 'Me contacter',
    'hero.stat1': "Annees d'experience",
    'hero.stat2': 'Projets realises',
    'hero.stat3': 'Clients satisfaits',

    // About
    'about.title': 'A <span class="accent">propos</span>',
    'about.p1': "Je suis un developpeur full stack passionne avec un sens aigu du design et un amour pour la creation d'experiences numeriques fluides. Fort de mon expertise dans les technologies web modernes, je transforme les idees en applications elegantes et fonctionnelles.",
    'about.p2': "Quand je ne code pas, vous me trouverez en train d'explorer de nouvelles technologies, de contribuer a l'open source ou de partager mes connaissances avec la communaute dev.",
    'about.name': 'Nom :',
    'about.location': 'Localisation :',
    'about.email': 'Email :',
    'about.availability': 'Disponibilite :',
    'about.status': 'Ouvert aux opportunites',
    'about.cv': 'Telecharger le CV',

    // Skills
    'skills.title': 'Mes <span class="accent">Competences</span>',
    'skills.design_desc': 'Figma, UI/UX, Design Responsive, Prototypage',

    // Projects
    'projects.title': 'Projets <span class="accent">Phares</span>',
    'projects.p1.name': 'Plateforme E-Commerce',
    'projects.p1.desc': "Boutique en ligne full-stack avec integration de paiement, inventaire en temps reel et tableau de bord administrateur.",
    'projects.p2.name': 'Application de Chat',
    'projects.p2.desc': "Application de messagerie en temps reel avec connexions WebSocket, partage de fichiers et canaux de groupe.",
    'projects.p3.name': 'Tableau de Bord Analytique',
    'projects.p3.desc': "Plateforme de visualisation de donnees avec graphiques interactifs, mises a jour en temps reel et fonctions d'export.",

    // Contact
    'contact.title': 'Me <span class="accent">Contacter</span>',
    'contact.desc': "Vous avez un projet en tete ou simplement envie de dire bonjour ? Je serais ravi d'echanger avec vous. Creons quelque chose d'incroyable ensemble.",
    'contact.location': 'Localisation',

    // Form
    'form.name': 'Votre nom',
    'form.email': 'Votre email',
    'form.subject': 'Sujet',
    'form.message': 'Votre message',
    'form.submit': 'Envoyer le message',
    'form.sent': 'Message envoye !',

    // Footer
    'footer.copy': '\u00a9 2026 John Doe. Tous droits reserves.',
  },

  en: {
    // Nav
    'nav.home': 'Home',
    'nav.about': 'About',
    'nav.skills': 'Skills',
    'nav.projects': 'Projects',
    'nav.contact': 'Contact',

    // Hero
    'hero.greeting': "Hello, I'm",
    'hero.title': 'Full Stack <span class="accent">Developer</span>',
    'hero.desc': 'I build modern web experiences with clean code and creative design.',
    'hero.cta1': 'View My Work',
    'hero.cta2': 'Get In Touch',
    'hero.stat1': 'Years Experience',
    'hero.stat2': 'Projects Done',
    'hero.stat3': 'Happy Clients',

    // About
    'about.title': 'About <span class="accent">Me</span>',
    'about.p1': "I'm a passionate full stack developer with a keen eye for design and a love for creating seamless digital experiences. With expertise in modern web technologies, I transform ideas into elegant, functional applications.",
    'about.p2': "When I'm not coding, you'll find me exploring new technologies, contributing to open source, or sharing knowledge with the dev community.",
    'about.name': 'Name:',
    'about.location': 'Location:',
    'about.email': 'Email:',
    'about.availability': 'Availability:',
    'about.status': 'Open to work',
    'about.cv': 'Download CV',

    // Skills
    'skills.title': 'My <span class="accent">Skills</span>',
    'skills.design_desc': 'Figma, UI/UX, Responsive Design, Prototyping',

    // Projects
    'projects.title': 'Featured <span class="accent">Projects</span>',
    'projects.p1.name': 'E-Commerce Platform',
    'projects.p1.desc': 'Full-stack online store with payment integration, real-time inventory, and admin dashboard.',
    'projects.p2.name': 'Chat Application',
    'projects.p2.desc': 'Real-time messaging app with WebSocket connections, file sharing, and group channels.',
    'projects.p3.name': 'Analytics Dashboard',
    'projects.p3.desc': 'Data visualization platform with interactive charts, real-time updates, and export features.',

    // Contact
    'contact.title': 'Get In <span class="accent">Touch</span>',
    'contact.desc': "Have a project in mind or just want to say hello? I'd love to hear from you. Let's create something amazing together.",
    'contact.location': 'Location',

    // Form
    'form.name': 'Your Name',
    'form.email': 'Your Email',
    'form.subject': 'Subject',
    'form.message': 'Your Message',
    'form.submit': 'Send Message',
    'form.sent': 'Message Sent!',

    // Footer
    'footer.copy': '\u00a9 2026 John Doe. All rights reserved.',
  }
};

let currentLang = localStorage.getItem('lang') || 'fr';

function setLang(lang) {
  currentLang = lang;
  localStorage.setItem('lang', lang);
  document.documentElement.lang = lang;

  const dict = translations[lang];

  // Translate text content
  document.querySelectorAll('[data-i18n]').forEach(el => {
    const key = el.getAttribute('data-i18n');
    if (dict[key] !== undefined) {
      if (el.hasAttribute('data-i18n-html')) {
        el.innerHTML = dict[key];
      } else {
        el.textContent = dict[key];
      }
    }
  });

  // Translate placeholders
  document.querySelectorAll('[data-i18n-placeholder]').forEach(el => {
    const key = el.getAttribute('data-i18n-placeholder');
    if (dict[key] !== undefined) {
      el.placeholder = dict[key];
    }
  });

  // Update toggle button
  const flagEl = document.getElementById('langFlag');
  if (flagEl) {
    flagEl.textContent = lang === 'fr' ? 'EN' : 'FR';
  }
}

function toggleLang() {
  setLang(currentLang === 'fr' ? 'en' : 'fr');
}

// Initialize on load
document.addEventListener('DOMContentLoaded', () => {
  const btn = document.getElementById('langToggle');
  if (btn) btn.addEventListener('click', toggleLang);

  // Apply saved language
  setLang(currentLang);
});
